num = int(input('Enter number from 0 - 5 '))
num1 = int(input('Enter number from 0 - 5 '))
num2 = int(input('Enter number from 0 - 5 '))
num3 = int(input('Enter number from 0 - 5 '))
num4 = int(input('Enter number from 0 - 5 '))
num5 = int(input('Enter number from 0 - 5 '))

print('num\t', 'square\t', 'cube\t')
print(num,'\t', num**2, '\t', num**3,'\t',)
print(num1,'\t', num1**2, '\t', num1**3,'\t',)
print(num2,'\t', num2**2, '\t', num2**3,'\t',)
print(num3,'\t', num3**2, '\t', num3**3,'\t',)
print(num4,'\t', num4**2, '\t', num4**3,'\t',)
print(num5,'\t', num5**2, '\t', num5**3,'\t',)
